### PR TITLE
Update tree.php

### PR DESCRIPTION
**Pull request by marr-th**
https://code.sigsiu.net/issues/1347#change-4088

good night

The error still occurs in IE.

I modified a couple of files and created a new one

Files are:
components/com_sobipro/lib/js/opt/field_category_tree.js
components/com_sobipro/lib/js/tree.js (I have the original file renamed to "tree-ori.js" , to work in the same way as before in the administrator)
components/com_sobipro/lib/mlo/tree.php

With these modifications, works in IE (from version 8 to the present). Chrome, Firefox. (others I have not tried)
Moreover, now may be added several caregorias simultaneously.(Problem I have seen some users complain)

Missing 3 things:

- Tweak the design, which is not as good as it should.

- change, constant language "'SP.JS_THIS_CATEGORY_HAS_BEEN_ALREADY_ADDED" = "one or more of the categories you have selected already added"

- That the parent category are not selectable when that configuration is chosen

I think that is a pretty good option
If not explained well, tell me

I hope your news
hope you like it
regards,

### CODE REVIEW

**Comment by Radek-Suski** [comment]
Could you please merge all your pull requests into one first. It is really hard to analyse your proposal when it's in 4 different pull requests.

**Comment by marr-th** [comment]
Hi Radek

Sorry, but I must be very clumsy.

Do not see how I can upload multiple files at once, in one pull request.

If you give me a hint, I'll do it gladly

regards

**Comment by marr-th** [comment]
Hello Radek

I do not know if you've looked at.

I would like to know what you think.

I think I deserve at least an answer. Whatever it

Regards

**Comment by SigsiuTrinity** [comment]
Hi,
as Radek said, please combine all your files into one pull request as it is very difficult to analyse your proposal if it is spread into 4 different pull requests.
Thank you

**Comment by marr-th** [comment]
Would be happy to merge.

The problem is not how it's done. It is the first time that use github and my English is not very good.

If you tell me how I can proceed will do it gladly

Thanks

**Comment by marr-th** [comment]
hello

Download the program windows and climbed the four files as you asked me.

Did you receive the pull request?

**Pull request closed without merging**
